version: '3.8'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Bartu.0408
      MYSQL_DATABASE: employeeSystem
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - 3307:3306

  backend:
    build: ./server
    ports:
      - 3001:3001
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build: ./client
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
